# Generated by Django 5.0.7 on 2025-09-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='status',
            field=models.CharField(default='complete', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='summary',
            constraint=models.UniqueConstraint(fields=('document',), name='one_summary_per_document'),
        ),
    ]
