# Generated by Django 5.0.7 on 2025-09-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_summary_status_summary_one_summary_per_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='complete', max_length=20),
        ),
    ]
