# Generated by Django 5.0.7 on 2025-09-15 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_summary_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['-created_at'], 'verbose_name': 'Summary', 'verbose_name_plural': 'Summaries'},
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this document was uploaded'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='The original uploaded file', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, help_text='The name of the file when it was uploaded', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='text_content',
            field=models.TextField(blank=True, help_text='Text content extracted from the document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(help_text='The user who uploaded this document', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='summary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this summary was created'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='detailed_notes',
            field=models.TextField(blank=True, help_text='Detailed bullet points covering main topics'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='document',
            field=models.ForeignKey(help_text='The document this summary belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='short_summary',
            field=models.TextField(blank=True, help_text='Brief summary for quick overview'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='status',
            field=models.CharField(choices=[('pending', 'Waiting to be processed'), ('processing', 'Currently being analyzed'), ('complete', 'Successfully processed'), ('failed', 'Processing failed')], default='complete', help_text='Current processing status of this summary', max_length=20),
        ),
    ]
